nm = input("What is your name?")
major = input("Whats your major?")
age = input("Whats your age?")
print("Salam hellooo",nm)
print("Welcome to our class!")
print("Your major",major,"is fun!")
print("Your age is",age,"years old")